name: Java CI Pipeline
#Bei push und pull wird workflow gestartet
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest #GitHub startet eine virtuelle Maschine

    steps:
      # Repository-Code auschecken
      - name: Checkout repository
        uses: actions/checkout@v4 #Lädt den Code aus GitHub in das virtuelle System herunter, 
                                  #damit die weiteren Schritte damit arbeiten können.

      # Java installieren
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build-Verzeichnis erstellen und kompilieren
      - name: Compile Java files
        run: |
          mkdir -p bin
          javac -d bin src/*.java

      # Testlauf (führt dein Main-Programm aus)
      - name: Run tests
        run: |
          echo "Starte manuelle Tests..."
          java -cp bin Main
